ARG PYTHON_VERSION=3.11.9
ARG ALPINE_VERSION=3.20

FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION}

ARG PHP_VERSION=8.3
ARG SWOOLE_VERSION=5.1.6
ARG PHPY_VERSION=1.0.6

RUN set -ex \
    && PHP_BUILD_VERSION=$(echo ${PHP_VERSION} | sed 's/\.//') \
    && apk update \
    && apk add --no-cache libstdc++ openssl c-ares-dev libpq-dev ca-certificates curl wget tar xz tzdata pcre \
    && apk add --no-cache --virtual .build-deps autoconf dpkg-dev dpkg file g++ gcc build-base ninja libffi-dev musl-dev linux-headers libc-dev make php${PHP_BUILD_VERSION}-dev php${PHP_BUILD_VERSION}-pear pkgconf re2c pcre-dev pcre2-dev zlib-dev libtool automake libaio-dev openssl-dev curl-dev \
    ## install python libary
    && pip install --upgrade pip \
    && pip install numpy opencv-python pandas scipy \
    ## install php
    && apk add \
    php${PHP_BUILD_VERSION} \
    php${PHP_BUILD_VERSION}-bcmath \
    php${PHP_BUILD_VERSION}-curl \
    php${PHP_BUILD_VERSION}-ctype \
    php${PHP_BUILD_VERSION}-dom \
    php${PHP_BUILD_VERSION}-fileinfo \
    php${PHP_BUILD_VERSION}-gd \
    php${PHP_BUILD_VERSION}-iconv \
    php${PHP_BUILD_VERSION}-mbstring \
    php${PHP_BUILD_VERSION}-mysqlnd \
    php${PHP_BUILD_VERSION}-openssl \
    php${PHP_BUILD_VERSION}-pdo \
    php${PHP_BUILD_VERSION}-pdo_mysql \
    php${PHP_BUILD_VERSION}-phar \
    php${PHP_BUILD_VERSION}-posix \
    php${PHP_BUILD_VERSION}-redis \
    php${PHP_BUILD_VERSION}-sockets \
    php${PHP_BUILD_VERSION}-sodium \
    php${PHP_BUILD_VERSION}-sysvshm \
    php${PHP_BUILD_VERSION}-sysvmsg \
    php${PHP_BUILD_VERSION}-sysvsem \
    php${PHP_BUILD_VERSION}-simplexml \
    php${PHP_BUILD_VERSION}-tokenizer \
    php${PHP_BUILD_VERSION}-zip \
    php${PHP_BUILD_VERSION}-zlib \
    php${PHP_BUILD_VERSION}-xml \
    php${PHP_BUILD_VERSION}-xmlreader \
    php${PHP_BUILD_VERSION}-xmlwriter \
    php${PHP_BUILD_VERSION}-pcntl \
    php${PHP_BUILD_VERSION}-opcache \
    && ln -sf /usr/bin/php${PHP_BUILD_VERSION} /usr/bin/php \
    ## install composer
    && cd /tmp \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
    ## install swoole
    && cd /tmp \
    && curl -SL "https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz" -o swoole.tar.gz \
    && mkdir -p swoole \
    && tar -xf swoole.tar.gz -C swoole --strip-components=1 \
    && ln -s /usr/bin/phpize${PHP_BUILD_VERSION} /usr/local/bin/phpize \
    && ln -s /usr/bin/php-config${PHP_BUILD_VERSION} /usr/local/bin/php-config \
    && ( \
        cd swoole \
        && phpize \
        && ./configure --enable-openssl --enable-swoole-curl --enable-cares \
        && make -s -j$(nproc) && make install \
    ) \
    && echo "memory_limit=1G" > /etc/php${PHP_BUILD_VERSION}/conf.d/00_default.ini \
    && echo "max_input_vars=PHP_INT_MAX" >> /etc/php${PHP_BUILD_VERSION}/conf.d/00_default.ini \
    && echo "opcache.enable_cli = 'On'" >> /etc/php${PHP_BUILD_VERSION}/conf.d/00_opcache.ini \
    && echo "extension=swoole.so" > /etc/php${PHP_BUILD_VERSION}/conf.d/50_swoole.ini \
    && echo "swoole.use_shortname = 'Off'" >> /etc/php${PHP_BUILD_VERSION}/conf.d/50_swoole.ini \
    # install phpy
    && cd /tmp \
    && curl -SL "https://github.com/swoole/phpy/archive/refs/tags/${PHPY_VERSION}.tar.gz" -o phpy.tar.gz \
    #&& curl -SL "https://github.com/swoole/phpy/archive/refs/heads/main.tar.gz" -o phpy.tar.gz \
    && mkdir -p phpy \
    && tar -xf phpy.tar.gz -C phpy --strip-components=1 \
    && ( \
        cd phpy \
        && phpize \
        && ./configure CFLAGS="-fPIC" --with-python-config=/usr/local/bin/python3-config \
        && make -s -j$(nproc) && make install \
    ) \
    && echo "extension=phpy.so" > /etc/php${PHP_BUILD_VERSION}/conf.d/50_phpy.ini \
    ## clear
    && apk del --purge *-dev .build-deps \
    && rm -rf /var/cache/apk/* /tmp/* /usr/share/man /usr/share/php* /usr/local/bin/php*